### ISSUE TITLE
Hub as service?

### ISSUE THREAD

**Issue by i3laze** [Jay-Rad/Adit#1]
Apparently, Hub server cannot be run as service.
"Server Options - Start with Windows" just makes it auto-launch in user context.

Please, upgrade "Unattended Access - Service" mode with hub feature.

P.S. Just did a workaround by using [NSSM.exe](https://nssm.cc/) and temporary disabling EFS-encryption over AuthKeys and ServerKey files.

**Comment by bitbound** [comment]
Unfortunately, I'm no longer working on Adit.  I've taken the relevant code and concepts into another project called Remotely.  Since I only have time for one project, this is the one I'll be working on going forward.

Feel free to check it out:  https://github.com/Jay-Rad/Remotely
